name: CI workflow

on:
  push:
    branches: [main, 'feature/**']
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 21 and cache Gradle
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Build project
        run: |
          ./gradlew --no-daemon build

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: app-jar
          path: build/libs/*.jar

  publish:
    name: Build image & Publish
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Download jar artifact
        uses: actions/download-artifact@v6
        with:
          name: app-jar
          path: build/libs

      - name: Lowercase repository name for image tag
        run: |
          echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:ci-${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest