name: Build and package

on:
  push:
    branches: [ main, master, feature/ci-build ]
  pull_request:
    branches: [ feature/ci-build ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build (Gradle)
    runs-on: ubuntu-latest
    env:
      GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Show repository name
        run: |
          echo "-----------------------------------------------"
          echo "Repository: ${{ github.event.repository.name }}"
          echo "Repo: ${{ env.GITHUB_REPOSITORY }}"

      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up JDK 21 and cache Gradle
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'gradle'
 
      - name: Build (package)
        run: ./gradlew --no-daemon --refresh-dependencies build -x test
 
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ env.GITHUB_USERNAME }}
            password: ${{ env.GITHUB_TOKEN }}
 
      - name: Build Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
#           file: ./Dockerfile
          push: false
          tags: |
            ghcr.io/${{ env.GITHUB_REPOSITORY }}:ci-${{ github.sha }}
            ghcr.io/${{ env.GITHUB_REPOSITORY }}:latest
 
      - name: Push image to GHCR
        run: |
            docker push ghcr.io/${{ env.GITHUB_REPOSITORY }}:ci-${{ github.sha }}
            docker push ghcr.io/${{ env.GITHUB_REPOSITORY }}:latest
 
      - name: Remove local images
        run: |
            docker image rm ghcr.io/${{ env.GITHUB_REPOSITORY }}:ci-${{ github.sha }}
            docker image rm ghcr.io/${{ env.GITHUB_REPOSITORY }}:latest
 